spring:
  application:
    name: FilmBuffsForum
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/film_buffs_forum
    username: postgres
    password: Qwerty2411.

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    generate-ddl: true

  thymeleaf:
    cache: false

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
app:
  jwt:
    secret: "very-long-super-secret-key-256-bits-minimum"
    access-expiration-ms: 900000        # 15 минут
    refresh-expiration-ms: 604800000    # 7 дней
  security:
    type: db
